## 🧠 Arquitetura VerifAI

```plantuml
@startuml verifica_ai
class Verifai
class Models
class InputHandler
class ContentProcessor
class OutputGenerator

Verifai --> Models
Verifai --> InputHandler
InputHandler --> ContentProcessor
ContentProcessor --> OutputGenerator
@enduml
