fake_base = [
    ("A notícia é completamente falsa, sem qualquer base em evidências reais ou documentos oficiais.", 0.08),
    ("Essa informação foi divulgada sem provas e já foi desmentida por veículos de checagem de fatos.", 0.12),
    ("Os dados apresentados são distorcidos com o objetivo claro de confundir ou manipular o público.", 0.19),
    ("A fonte utilizada não possui qualquer respaldo científico ou histórico de confiabilidade.", 0.14),
    ("A postagem está recheada de teorias conspiratórias infundadas e já refutadas diversas vezes.", 0.10),
    ("Especialistas já desmentiram essa notícia, classificando-a como completamente falsa.", 0.09),
    ("O conteúdo é sensacionalista, repleto de exageros e sem nenhuma precisão informativa.", 0.13),
    ("A informação enganosa circula há tempos na internet e já foi desmentida diversas vezes.", 0.17),
    ("Esse boato foi amplamente divulgado, mas não há nenhuma comprovação concreta sobre ele.", 0.18),
    ("O relato não apresenta nenhuma evidência confiável e é incompatível com os fatos conhecidos.", 0.11),
    ("O vídeo viral apresenta informações distorcidas que já foram negadas por fontes oficiais confiáveis.", 0.10),
    ("A publicação repete mentiras já desmentidas por diversas agências de verificação independentes.", 0.07),
    ("O conteúdo ignora completamente os dados científicos e usa argumentos apelativos e falsos.", 0.15),
    ("A notícia se baseia em boatos sem nenhuma fonte confiável, servindo apenas para gerar medo.", 0.16),
    ("Não há qualquer comprovação de que o fato relatado tenha ocorrido conforme descrito na postagem.", 0.13),
    ("O conteúdo é claramente manipulado para induzir o leitor ao erro, sem base factual alguma.", 0.09),
    ("A manchete distorce os fatos de forma alarmista e sem o devido embasamento técnico.", 0.19),
    ("Trata-se de um boato que circula há anos e sempre foi desmentido pelas autoridades competentes.", 0.14),
    ("A imagem usada foi retirada de contexto e serve apenas para reforçar uma narrativa falsa.", 0.12),
    ("As fontes citadas não existem ou são completamente irrelevantes para o conteúdo afirmado.", 0.11),
    ("O texto ignora fatos históricos amplamente conhecidos e validados, sugerindo algo absurdo.", 0.08),
    ("Essa teoria da conspiração já foi refutada várias vezes, inclusive por especialistas da área.", 0.10),
    ("A informação se baseia em suposições infundadas, sem nenhuma evidência verificável.", 0.17),
    ("O artigo faz alegações extraordinárias sem fornecer qualquer prova concreta ou documentada.", 0.18),
    ("Esse tipo de conteúdo circula em redes sociais, mas é considerado completamente falso.", 0.13),
    ("Não há qualquer estudo ou dado que sustente essa informação divulgada de forma irresponsável.", 0.19),
    ("A postagem deturpa estatísticas reais para promover desinformação entre os leitores.", 0.12),
    ("A fonte do conteúdo é um blog sensacionalista já conhecido por espalhar desinformação.", 0.16),
    ("Essa alegação contradiz completamente dados oficiais amplamente divulgados.", 0.09),
    ("Mesmo após várias investigações, nenhuma prova foi encontrada que sustente essa afirmação.", 0.15),
    ("Essa afirmação contradiz completamente os fundamentos da astronomia moderna. Desde Galileu Galilei, observações empíricas e evidências fotográficas, satélites e leis da gravitação comprovam que a Terra é aproximadamente esférica e orbita o Sol em um sistema heliocêntrico. A ciência atual rejeita qualquer hipótese terraplanista.", 0.01),
    ("Essa é uma teoria conspiratória sem fundamento científico. Nenhuma evidência técnica ou médica sustenta a presença de dispositivos de rastreamento em vacinas. Fabricantes de vacinas são fiscalizados por agências de regulação como a Anvisa, FDA e OMS. A teoria foi desmentida por diversos especialistas em saúde pública.", 0.02),
    ("Essa alegação já foi amplamente refutada. Evidências como os retro-refletores deixados na Lua, transmissões ao vivo, fotografias, registros técnicos e relatos dos astronautas confirmam as missões Apollo. Teorias de que tudo teria sido encenado são infundadas e contradizem múltiplas fontes independentes.", 0.07),
]

indeterm_base = [
    ("Essa informação ainda não foi confirmada por fontes confiáveis, sendo necessário aguardar novas atualizações.", 0.35),
    ("A notícia apresenta dados incompletos e pouco claros, dificultando uma verificação definitiva.", 0.42),
    ("O relato precisa ser investigado mais a fundo antes de se chegar a qualquer conclusão concreta.", 0.38),
    ("Dados preliminares indicam possibilidades, mas nenhuma confirmação oficial foi divulgada até o momento.", 0.46),
    ("A informação envolve controvérsias, com especialistas e fontes divergindo quanto à sua veracidade.", 0.50),
    ("Há aspectos verdadeiros e outros duvidosos no conteúdo, o que torna sua classificação difícil.", 0.55),
    ("Apesar de apresentar indícios, não há uma confirmação definitiva por parte das autoridades.", 0.40),
    ("O relato é baseado em testemunhos ainda não verificados, exigindo mais apuração.", 0.34),
    ("O conteúdo ainda está em análise e não há consenso sobre a veracidade total da informação.", 0.44),
    ("Os dados apresentados são parciais, e há ausência de evidências concretas para confirmar os fatos.", 0.60),
    ("A narrativa contém elementos plausíveis, mas faltam evidências diretas para comprovação completa.", 0.48),
    ("O estudo citado está em fase inicial e ainda não passou por revisão por pares.", 0.36),
    ("Especialistas ainda não chegaram a um consenso sobre as implicações dessa descoberta.", 0.52),
    ("As informações estão sendo apuradas e podem mudar conforme novas evidências surgirem.", 0.46),
    ("A fonte tem certo grau de confiabilidade, mas carece de transparência nos dados fornecidos.", 0.58),
    ("O conteúdo mistura fatos reais com hipóteses que ainda não foram validadas oficialmente.", 0.54),
    ("Ainda não foi publicada nenhuma nota oficial confirmando ou negando essa informação.", 0.33),
    ("A postagem levanta pontos interessantes, mas sem documentos que sustentem a narrativa.", 0.49),
    ("A verificação está em andamento e até o momento não há confirmação definitiva.", 0.39),
    ("O caso está em investigação e muitas dúvidas permanecem sem resposta.", 0.37),
    ("Os especialistas estão divididos quanto à interpretação dos dados apresentados.", 0.55),
    ("A evidência apresentada é insuficiente para determinar com certeza a veracidade dos fatos.", 0.53),
    ("Há lacunas importantes no conteúdo que impedem uma conclusão categórica.", 0.51),
    ("Essa afirmação pode ter algum fundamento, mas ainda não há elementos que a comprovem.", 0.41),
    ("O conteúdo reflete uma suspeita que ainda precisa ser confirmada pelas autoridades.", 0.45),
    ("A notícia está sendo analisada por verificadores independentes.", 0.43),
    ("O fato foi citado, mas não está presente em fontes oficiais ainda.", 0.47),
    ("A linguagem é vaga e não há menção a documentos ou fontes confiáveis.", 0.40),
    ("Apesar da repercussão, a história segue como não confirmada pelas autoridades.", 0.50),
    ("As informações ainda não foram atualizadas pelos meios oficiais.", 0.38),
    ("Apesar de haver uma tendência global de transição para veículos elétricos, com legislações em alguns países europeus para banir carros a combustão até meados do século, fatores como infraestrutura de carregamento, acesso a tecnologias, políticas públicas e interesses econômicos ainda tornam incerta uma substituição total até 2040.", 0.55),
    ("Diversos especialistas apontam que a IA causará mudanças significativas no mercado de trabalho, com automação de tarefas repetitivas. No entanto, ainda há muitas incertezas sobre a extensão dessa substituição, especialmente em áreas que requerem julgamento humano, empatia ou criatividade.", 0.48),
    ("Os Maias tinham um calendário avançado e um conhecimento astronômico admirável para sua época, sendo capazes de prever eclipses com razoável precisão. No entanto, associar essas previsões a precisão moderna ou interpretações místicas é controverso entre historiadores e arqueoastrônomos.", 0.50)
]

fato_base = [
    ("Essa informação foi confirmada por múltiplas fontes confiáveis e está presente em documentos oficiais amplamente acessíveis.", 0.95),
    ("A notícia foi validada por agências oficiais e corroborada por entidades de renome no setor.", 0.91),
    ("Os dados apresentados são compatíveis com estatísticas oficiais e já foram divulgados por órgãos públicos.", 0.88),
    ("O conteúdo da publicação está embasado em estudos científicos revisados por pares e amplamente citados.", 0.94),
    ("Relatos semelhantes foram confirmados por especialistas e por veículos tradicionais da imprensa.", 0.89),
    ("A informação foi checada por múltiplas agências independentes e todas confirmaram sua veracidade.", 0.92),
    ("Há evidências robustas e documentação oficial que sustentam os dados apresentados na notícia.", 0.87),
    ("O relato está baseado em dados públicos, pesquisas reconhecidas e fontes oficiais atualizadas.", 0.90),
    ("O conteúdo passou por processo rigoroso de checagem e foi aprovado por revisores especializados.", 0.93),
    ("Essa afirmação já foi confirmada por vários estudos acadêmicos e não apresenta controvérsias atuais.", 0.97),
    ("As informações são consistentes com documentos legais e registros públicos oficiais.", 0.96),
    ("Especialistas de instituições respeitadas validaram todos os dados apresentados.", 0.90),
    ("A notícia segue diretrizes editoriais de verificação e passou por avaliação interna rigorosa.", 0.88),
    ("Estudos internacionais confirmaram os dados mencionados na publicação.", 0.91),
    ("As autoridades já se pronunciaram oficialmente confirmando todos os pontos do relato.", 0.94),
    ("O conteúdo foi publicado em veículo reconhecido por sua credibilidade jornalística.", 0.89),
    ("A afirmação é compatível com dados históricos amplamente aceitos pela comunidade científica.", 0.87),
    ("Pesquisas independentes reforçam a validade dos dados divulgados nesta notícia.", 0.92),
    ("A checagem cruzada entre diferentes fontes confirma a autenticidade do conteúdo.", 0.93),
    ("Essa informação é referenciada em diversas bases de dados governamentais atualizadas.", 0.96),
    ("A notícia cita diretamente documentos oficiais disponíveis ao público.", 0.91),
    ("A publicação apresenta evidências claras, verificáveis e embasadas na realidade.", 0.90),
    ("O conteúdo foi auditado por especialistas antes da sua liberação ao público.", 0.95),
    ("A afirmação é parte de relatórios oficiais divulgados por instituições internacionais.", 0.94),
    ("Todos os dados coincidem com números divulgados por organizações oficiais confiáveis.", 0.89),
    ("A checagem feita por agências independentes não identificou nenhuma inconsistência.", 0.90),
    ("Relatos de campo e documentos formais sustentam integralmente essa informação.", 0.93),
    ("Essa afirmação foi usada como base para políticas públicas, o que reforça sua credibilidade.", 0.95),
    ("O dado foi replicado por jornais de grande circulação após confirmação com órgãos competentes.", 0.92),
    ("Trata-se de um fato consolidado e amplamente aceito no meio científico.", 0.97),
    ("A colonização portuguesa no Brasil começou oficialmente em 1500 com a chegada de Pedro Álvares Cabral e durou até 1822, quando foi declarada a independência. Durante esse período, o território brasileiro foi administrado por governadores enviados pela Coroa Portuguesa, submetido ao sistema colonial de exploração, como o ciclo do pau-brasil, do açúcar e do ouro.", 0.96),
    ("A Organização Mundial da Saúde recomenda amplamente a vacinação contra a poliomielite como forma segura e comprovadamente eficaz de erradicar a doença. Dados de campanhas globais mostram que países que adotaram amplamente a vacina tiveram quedas drásticas nos casos, com erradicação completa em algumas regiões.", 0.92),
    ("De acordo com a classificação estelar moderna, o Sol é classificado como uma estrela da sequência principal do tipo G2V, o que significa que ele é uma estrela amarela de tamanho médio, baseada em sua temperatura superficial (~5778 K) e seu espectro de emissão. Esse dado é amplamente aceito pela comunidade astronômica internacional.", 0.89)
]